"Content: Advanced HTML/CSS":
  - changed-files:
      - any-glob-to-any-file: "advanced_html_css/**/*"

"Content: Databases":
  - changed-files:
      - any-glob-to-any-file: "databases/**/*"

"Content: Getting Hired":
  - changed-files:
      - any-glob-to-any-file: "getting_hired/**/*"

"Content: Git":
  - changed-files:
      - any-glob-to-any-file: "git/**/*"

"Content: Intermediate HTML/CSS":
  - changed-files:
      - any-glob-to-any-file: "intermediate_html_css/**/*"

"Content: JavaScript":
  - changed-files:
      - any-glob-to-any-file: "javascript/**/*"

"Content: NodeJS":
  - changed-files:
      - any-glob-to-any-file: "nodeJS/**/*"

"Content: React":
  - changed-files:
      - any-glob-to-any-file: "react/**/*"

"Content: Ruby":
  - changed-files:
      - any-glob-to-any-file: "ruby/**/*"

"Content: Ruby on Rails":
  - changed-files:
      - any-glob-to-any-file: "ruby_on_rails/**/*"

"Content: Foundations":
  - changed-files:
      - any-glob-to-any-file: "foundations/**/*"

"Content: Markdownlint":
  - changed-files:
      - any-glob-to-any-file:
          - "markdownlint/**/*"
          - "**/*.markdownlint-cli2.jsonc"

"Type: Chore":
  - changed-files:
      - any-glob-to-any-file: "archive/**/*"
