sudo: required
language: ruby
rvm:
  - 2.6.2
services:
  - postgresql
before_script:
  - bundle install
  - psql -c 'create database theodinproject_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rails db:schema:load
  - bundle exec rubocop
  - bundle exec rspec
deploy:
  provider: heroku
  strategy: git
  edge: true
  api_key:
    secure: mQVwLlrNOjZKdoI4TlZAiWayX7FFc8bI9yglHxa1L7LMQUWKQdJIduCe78wHCAYc/vyu896+N9PIXSxoU6GHs1JomMEC7mxHZOrjyY6XIZQL4tAi2DHsKO1AkF4flTovNXZH/khn5XGLHkHgDNotYglHBsRkwKC7Gu/1s5rmRup5A2X9tvMfHJ8kFCK3DK0qoP6ZFxLR9FvBfEzc+erP1iinCcjPsf2eFrlUC9NJWVk6Thf0fXF185DkXs4F/te0DwHPrrzzw5Nb4fzX+id6kPmzffW0bTAKqIuNSO79Sau8t07w/zxacZk2QsGgPKPLgEj4oIY+afbM9VlETKL+KHwHDXlrYef0Wdrj60MQEpsnbl5EUvTmO+6Cmugf51mBjHbYRttFLTHF+4vEXg2NLIn+vtHnS43QA05OxIq0LyhP2pGJz1moE05bw9mksCQKPbs5e1VE2DEN8YN+SqKC8lDeoFxeyIHT6o6CZVdubmNXXLomhgyCbvIlYABc2aTgSs8NPw7Qum8TgNeHsBBqEzMXITpgWb/g5chF3V6n5JSZn/kZ42Fn09RyeN7TjwTUH7Xu69oTagfLLdL5p2LalzpYOJAdZ0ygDSSu7vj7aFIHEilNYZc5EHPISRVFhVi3P+M/bHrY/w1U0ZEQMeBlqwi/y8ZjnGcz3oEpHXuyrQw=
  app: theodinproject
  on:
    branch: master
