version: "3.8"
services:
  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: theodinproject
      POSTGRES_DB: theodinproject
  web:
    build: .
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: theodinproject
      POSTGRES_DEV_DB: theodinproject_development
      POSTGRES_HOST: db

volumes:
  postgres-data:
