source 'https://rubygems.org'
ruby '~> 2.6'

gem 'rails', '6.1.3.2'

gem 'activeadmin'
gem 'activeadmin_addons', '~> 1.7.1'
gem 'active_material'
gem 'acts_as_votable'
gem 'bootstrap', '4.6.0'
gem 'cancancan'
gem 'devise', '>= 4.7.1'
gem 'discard', '~> 1.2'
gem 'discordrb-webhooks'
gem 'dry-initializer', '~> 3.0.4'
gem 'friendly_id', '~> 5.4'
gem 'gibbon', '~> 3.4.0'
gem 'github_api', '~> 0.19'
gem 'github_webhook', '~> 1.1.2'
gem 'jquery-rails', '~> 4.4.0'
gem 'kaminari', '~> 1.2'
gem 'kramdown', '>= 2.3.1'
gem 'newrelic_rpm'
gem 'nokogiri', '~> 1.11.5'
gem 'noticed', '~> 1.4'
gem 'octokit', '~> 4.21'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'omniauth-rails_csrf_protection'
gem 'pg', '~> 1.2'
gem 'premailer-rails', '~> 1.11'
gem 'puma'
gem 'rack-attack'
gem 'react-rails'
gem 'ruby-progressbar', '~> 1.11.0'
gem 'sass-rails', '~> 6.0'
gem 'seed-fu', '~> 2.3.9'
gem 'sentry-rails', '~> 4.5.0'
gem 'sentry-ruby', '~> 4.5.0'
gem 'sidekiq'
gem 'sprockets', '~> 3.7.2'
gem 'turbolinks'
gem 'uglifier', '~> 4.2'
gem 'webpacker'

group :development, :test, :docker do
  gem 'capybara'
  gem 'climate_control'
  gem 'cuprite'
  gem 'dotenv-rails'
  gem 'factory_bot'
  gem 'factory_bot_rails', '~> 6'
  gem 'pry', '~> 0.14.1'
  gem 'rails-controller-testing'
  gem 'rake', '~> 13.0'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'vcr', '~> 6.0'
  gem 'webmock', '~> 3.13'
end

group :development, :docker do
  gem 'better_errors'
  gem 'binding_of_caller', '~> 1.0'
  gem 'derailed'
  gem 'letter_opener', '~> 1.4'
  gem 'listen'
  gem 'reek'
  gem 'rubocop', '>= 1.12.1', require: false
  gem 'rubocop-performance', '>= 1.10.2', require: false
  gem 'web-console'
end
