name: ⛓️‍💥 Broken Link
description: Point out a broken or dead link in our curriculum
title: '<Course>: <Short description of the broken link>'
labels: ["Status: Needs Triage"]
assignees:
  - nil
body:
  - type: markdown
    attributes:
      value: |
        Before opening a suggestion for a broken link, please check the link again in 3-24 hours. More often than not, the website is down temporarily.

        If the website is still down, ask other people in our Discord community to confirm that the link is also broken for them.

  - type: checkboxes
    id: contributing
    attributes:
      label: Checks
      description: Please fill out the following checkboxes
      options:
        - label: I have confirmed that the link is still broken after 3-24 hours of my initial discovery.
          required: true
        - label: I have confirmed in the Discord community that others are having the same issue with this link.
          required: false
        - label: This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
          required: true
        - label: I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
          required: true
        - label: Would you like to work on this issue?
          required: false
  - type: textarea
    id: suggested-changes
    attributes:
      label: Description of the broken link
      description: Please describe where the link is in the lesson
      placeholder: ex 'The link to the blog in the first assignment is broken.'
    validations:
      required: true
  - type: dropdown
    id: path
    attributes:
      label: Path
      description: Which path does your suggestion affect?
      multiple: true
      options:
        - Foundations
        - Ruby / Rails
        - Node / JS
        - Other / NA
    validations:
      required: true
  - type: input
    id: lesson-link
    attributes:
      label: Lesson Url
      description: A link to the relevant lesson or page
      placeholder: ex. https://www.theodinproject.com/lessons/ruby-how-this-course-will-work
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: (Optional) Discord Name
      description: Optionally provide your discord name to help coordinate changes there if necessary
      placeholder: ex. odinite
    validations:
      required: false
  - type: textarea
    id: additional-comments
    attributes:
      label: (Optional) Additional Comments
      description: "Anything else you'd like to cover"
      placeholder: We ❤️ open source
    validations:
      required: false
